### ISSUE TITLE
avy-zap doesn't work while recording a macro

### ISSUE THREAD

**Issue by DamienCassou** [cute-jumper/avy-zap#1]
I bound `avy-zap-to-char` to `M-z` and I'm happy with it. I like to have avy-like completion all the times so I didn't use `avy-zap-to-char-dwim`. The problem is that `avy-zap-to-char` is not appropriate when recording a macro because the `avy-keys` are not predictable. In other words, recording the macro will work, but playing it will have unexpected results. I guess the problem is the same when multicursors is activated.

Would it be possible to have a smarter dwim version that uses avy-like completion by default but reverts to standard zapping in some contexts?

**Comment by cute-jumper** [comment]
I guess these two variables, `defining-kdb-macro` and `executing-kbd-macro`, would help. I will come back to this issue as soon as I could access my laptop, or if you will, you could try and submit a pull request if this approach works:-)

**Comment by DamienCassou** [comment]
Junpeng Qiu notifications@github.com writes:

> I guess these two variables, `defining-kdb-macro` and `executing-kbd-macro`, would help. I will come back to this issue as soon as I could access my laptop, or if you will, you could try and submit a pull request if this approach works:-) 

thanks for your answer. My plate is full at the moment, sorry. And I
would feel more confident when changing anything if the projects had
tests :-).

## 

Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by cute-jumper** [comment]
Sure. I'll try to solve this later. Thanks:-)

**Comment by cute-jumper** [comment]
Sorry for the late reply. I have been quite busy these days. So after a quick try, the newest version should work. If you find any problem, please let me know. Thanks!

**Comment by DamienCassou** [comment]
Thank you very much!
