### ISSUE TITLE
avy-zap-to-char-dwim and avy-zap-up-to-char-dwim have inconsistent docstring vs implementation

### ISSUE THREAD

**Issue by squid-lee** [cute-jumper/avy-zap#2]
In both avy-zap-up-to-char-dwim and avy-zap-to-char-dwim the doc string says `Without PREFIX call zap-to-char`.

However, without a prefix, `avy-zap-to-char` (or `...-up-to...`) is invoked instead, and adding a prefix calls the non avy version.

**Comment by cute-jumper** [comment]
You're right. I forgot to modify the docstring accordingly. It should be fixed now. Thank you for reporting this!
